kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/anjoseph/parca-data
        containerPath: /parca-data
  - role: worker
    extraMounts:
      - hostPath: /home/anjoseph/parca-data
        containerPath: /parca-data
  - role: worker
    extraMounts:
      - hostPath: /home/anjoseph/parca-data
        containerPath: /parca-data

