apiVersion: v1
data:
  parca.yaml: |-
    "object_storage":
      "bucket":
        "config":
          "directory": "/var/lib/parca"
        "type": "FILESYSTEM"
    "scrape_configs":
      - "job_name": "argocd-application-controller"
        "scrape_interval": "10s"
        "static_configs":
          - "targets": [ 'argocd-metrics.argocd.svc.cluster.local:8082' ]
      - "job_name": "argocd-server"
        "scrape_interval": "10s"
        "static_configs":
          - "targets": [ 'argocd-server-metrics.argocd.svc.cluster.local:8083' ]
      - "job_name": "argocd-applicationset-controller"
        "scrape_interval": "10s"
        "static_configs":
          - "targets": [ 'argocd-applicationset-controller.argocd.svc.cluster.local:8080' ]
      - "job_name": "argocd-notifications-controller"
        "scrape_interval": "10s"
        "static_configs":
          - "targets": [ 'argocd-notifications-controller-metrics.argocd.svc.cluster.local:9001' ]
      - "job_name": "argocd-repo-server"
        "scrape_interval": "10s"
        "static_configs":
          - "targets": [ 'argocd-repo-server.argocd.svc.cluster.local:8084' ]
kind: ConfigMap
metadata:
  name: parca
  namespace: parca
