apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parca-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: crc-csi-hostpath-provisioner
  volumeMode: Filesystem

